language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

sudo: false

install:
  - "pip install -r requirements.txt"
  - "pip install pep8"
  - "pip install nose==1.3.7"
  - "python setup.py install"

script:
  - pep8 dnsyo
  - dnsyo -q 25 -t 10 example.com A
  - nosetests -v
